# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefigures',
            name='order',
            field=models.IntegerField(help_text='Figure display order.', verbose_name='Order'),
        ),
    ]
