# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180113_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Uri identifier for this department.', max_length=100, verbose_name='Slug'),
        ),
    ]
