# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180114_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Uri identifier for this Article.', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Uri identifier for this category.', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
